# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Store Crawler

on:
  workflow_dispatch:
  schedule: 
    - cron: '0 */3 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0             # otherwise, you will fail to push refs to dest repo
    - name: Set up Python 3.11.6
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: 'pip'
    - run: pip install -r requirements.txt

    - name: Start Store Crawler
      run: |
        python3 prismat/storecrawler.py

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        rebase: true
        branch: 'master'