# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Store Crawler

on:
  workflow_dispatch:
  schedule: 
    - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.6
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.6"
    - name: Install dependencies
      run: |
        echo 'Installing python'
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Start Store Crawler
      run: |
        echo 'Store Crawler :: started'
        python3 prismat/storecrawler.py
        echo 'Store Crawler :: done'
